### ISSUE TITLE
error: Recipe `demo-vm` failed on line 20 with exit code 1

### ISSUE THREAD

**Issue by pearapple123** [FedericoSchonborn/budgie-nix#16]
Ran `just demo-vm` and it returned:
```
rm: cannot remove '*.qcow2': No such file or directory
error: Recipe `demo-vm` failed on line 20 with exit code 1
```
I ran the binary in `./result/bin/` and it works, so maybe this is just a warning?

Nix info:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.758.e8ec26f41fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(mips): `""`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FedericoSchonborn** [comment]
That line was supposed to remove the disk image generated by the VM so if I changed the theme or something it didn't affect the default settings in the next boot, guess I never ran it *without* a disk image being present 🤦. You can remove it.
