### ISSUE TITLE
No recipe `run-vm` in Justfile

### ISSUE THREAD

**Issue by pearapple123** [FedericoSchonborn/budgie-nix#17]
Justfile doesn't contain a `run-vm` recipe so running `just run-vm` gets `error: Justfile does not contain recipe `run-vm`.`. However, README.md says that this is the command for running the setup in a vm.

I think the correct command should be `demo-vm`, since asides from #16 it works fine.

**Comment by FedericoSchonborn** [comment]
Yeah, the README is *really* outdated, you should use `demo-vm` and `install-iso-vm`.
