### ISSUE TITLE
Enable libinput by default?

### ISSUE THREAD

**Issue by bobby285271** [FedericoSchonborn/budgie-nix#22]
I wonder if it makes sense to enable libinput by default in Budgie module. Something like `services.xserver.libinput.enable = mkDefault true;`.

Budgie control center probably has some [support](https://github.com/search?q=repo%3ABuddiesOfBudgie%2Fbudgie-control-center%20libinput&type=code) for that and also this is now enabled in every desktops:

- https://github.com/NixOS/nixpkgs/issues/170489

**Comment by FedericoSchonborn** [comment]
Done.
