### ISSUE TITLE
Wrong Budgie version number in budgie-control-center

### ISSUE THREAD

**Issue by bobby285271** [FedericoSchonborn/budgie-nix#23]
Same as https://discourse.nixos.org/t/why-does-gnome-settings-show-gnome-3-0-even-though-its-3-30/2745, the version number in budgie-control-center is hardcoded as 3.0, likely because it cannot find budgie-version.xml:

https://github.com/BuddiesOfBudgie/budgie-control-center/blob/v1.1.1/panels/info-overview/cc-info-overview-panel.c#L157
https://github.com/BuddiesOfBudgie/budgie-control-center/blob/v1.1.1/panels/info-overview/cc-info-overview-panel.ui#L133

<img src="https://user-images.githubusercontent.com/20080233/211994691-6b7a4dbc-23dd-456a-a8e8-67449b303264.jpg" width=80%>

Does it make sense to apply something similar to https://github.com/NixOS/nixpkgs/commit/a0bb3dd8ac4fb1e0c5fa4b897b97b7b5e79a5f31 here as well? Or do you know any proper ways to fix this upstream? GNOME is currently reading the version [from gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5406) instead.

**Comment by bobby285271** [comment]
Ah too lazy to file one more issue, the disk capacity in the screenshot is shown as "Unknown", having `services.udisks2.enable` here probably helps, not sure if that should be added by default too.

**Comment by FedericoSchonborn** [comment]
> Does it make sense to apply something similar to https://github.com/NixOS/nixpkgs/commit/a0bb3dd8ac4fb1e0c5fa4b897b97b7b5e79a5f31 here as well? Or do you know any proper ways to fix this upstream? GNOME is currently reading the version [from gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5406) instead.

I guess I will need to make a proper patch instead of copying the one from GNOME Control Center.

> Ah too lazy to file one more issue, the disk capacity in the screenshot is shown as "Unknown", having services.udisks2.enable here probably helps, not sure if that should be added by default too.

I added that yesterday :)
